### ISSUE TITLE
no-live vs. exit

### ISSUE THREAD

**Issue by okdistribute** [hypercore-protocol/cli#16]
In our user experience research with the dat cli, we found that `--exit` was more immediately intuitive than `--live=false`, seems like that crept in again with the `hyp` cli!

**Comment by pfrazee** [comment]
Yeah +1 Karissa, @andrewosh I kind of feel like it shouldn't be live by default. What do yall think about reversing it so that you have to add `--live` instead?

**Comment by fwip** [comment]
Additionally, it looks like the `hyp info` command doesn't have an option to not be live, which was one of the first surprising things to me I ran into. (Would have expected it to be similar to `git status` - to just output a snapshot of what's going on.)

**Comment by pfrazee** [comment]
@fwip yeah that makes sense. Live-by-default is a little surprising

**Comment by pfrazee** [comment]
Okay talked it through with andrew and he agrees, going to change `sync` and `info` for this.

**Comment by pfrazee** [comment]
Published `1.2.0`
