### ISSUE TITLE
hyp output to stdout

### ISSUE THREAD

**Issue by rzelnik** [hypercore-protocol/cli#23]
It would be great to redirect hyp text output to stdout, so that it would be redirected into file, filtered through pipe with grep, etc.

**Comment by pfrazee** [comment]
@rzelnik yeah are there any commands in particular you wanted this for? Would help us prioritize those

**Comment by rzelnik** [comment]
hyp info: I seed many drives, so the list overflows the terminal screen. Export into file or paging through 'more' would be helpful.

**Comment by rzelnik** [comment]
For me this is a feature request with lowest possible priority.

**Comment by pfrazee** [comment]
Yeah no prob, wrapping a big website update this week, can prob hit this next week

**Comment by pfrazee** [comment]
Okay should be fixed in 1.3.0
