### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by JerryGreen** [hypercore-protocol/cli#24]
I installed `hyp` and tried to use `ls` command from the README:

```bash
hyp ls hyper://515bbbc1db2139ef27b6c45dfa418c8be6a1dec16823ea7cb9e61af8d060049e/
```

![image](https://user-images.githubusercontent.com/13215662/102485237-27f50b80-4089-11eb-8787-fd1904c6ecdc.png)

Other commands don't work either:

![image](https://user-images.githubusercontent.com/13215662/102485694-c6816c80-4089-11eb-95ce-302257bb2e66.png)

## Context

Node version: v14.15.2
Bash version: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

**Comment by andrewosh** [comment]
Thanks for the issue @JerryGreen. Are you on Windows?

**Comment by JerryGreen** [comment]
@andrewosh yup

**Comment by andrewosh** [comment]
Gotcha. Windows testing is definitely our weakness :) We'll look into this!

**Comment by JerryGreen** [comment]
@andrewosh might worth mentioning, that I used the "Git Bash" (NOT `cmd.exe`), - a windows-version of Bash, which comes together with [git scm](https://git-scm.com/download/win) (which is pretty much the same GNU Bash, except it copies files when using `ln` commands, instead of creating symlinks, because Windows doesn't support symlinks).

Though I'm not sure if it's a problem with Bash, - also likely the problem with Node. Can't say for sure.

**Comment by pfrazee** [comment]
Fixed in `1.3.1`. We were spawning the daemons by calling the `.js` files, which depends on the she-bang behavior which ofc windows doesn't support. Fixed by changing the spawn command to `node <daemon-script>`.

**Comment by JerryGreen** [comment]
Works like a charm now! Thanks

Though there are still some quirks elsewhere, for example `hyp version`:

![image](https://user-images.githubusercontent.com/13215662/102695798-63d7ce80-424b-11eb-9941-217932967879.png)

Even though it installed `1.3.1`:

![image](https://user-images.githubusercontent.com/13215662/102695699-cda3a880-424a-11eb-935e-4cf413171cfb.png)

`0.0.2` is a version listed in my current folder's `package.json`, - if I `cd` into another project, `hyp --version` shows another version. Not sure if it's related to some Windows stuff, or what is that. Not crucial, so gonna play with this thing anyway :) Thanks again

**Comment by pfrazee** [comment]
Ahh lovely, thanks. I'll file another issue
