### ISSUE TITLE
--yes option for scripted use

### ISSUE THREAD

**Issue by Treora** [hypercore-protocol/cli#42]
For example, to run `hyp sync` in a cron job once every hour, it would help if hyp skips checking for confirmation (currently it asks `Begin sync? [y/N]`). Several command line tools have a `-y`/`--yes` or similar option to always assume the answer is yes. Could hyp get this too?

**Comment by dym-sh** [comment]
yes, you can add `-y` to bypass all additional user-input

https://github.com/hypercore-protocol/cli/blob/master/lib/commands/drive/sync.js#L45
